system:
  host: 0.0.0.0
  port: 8080
  env: debug
  start_time: "2024-08-06"
  machine_id: 1
log:
  level: "info"
  filename: "web_server.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: tap_db
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: "redis"
  db: 0
  pool_size: 100
es:
  host: 127.0.0.1
  port: 9200
email:
  host: smtp.qq.com
  port: 465
  user:
  password:
  default_from_email:
  use_ssl: true
  user_tls: false
jwt:
  secret: '2024724'
  expires: 20
  issuer: "server"
etcd:
  host: 127.0.0.1
  port: 2379
captcha:
  key_long: 6
  img_width: 240
  img_height: 80

