basePath: /
host: 127.0.0.1:8080
info:
  contact:
    email: 1790146932@qq.com
    name: Axios
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Template
  version: "1.0"
paths: {}
swagger: "2.0"
